package com.jayraj.churnpredictor;

/** GENERATED by tools/generate_model.py: real customers with scikit-learn's own predictions. */
final class GoldenData {
    private GoldenData() {}

    /** tenure, monthlyCharges, contract, internet, payment, then 12 booleans, then probability. */
    static final Object[][] ROWS = {
        new Object[] { 59, 75.95, "Two year", "DSL", "Credit card (automatic)", false, true, false, true, true, true, true, false, true, true, true, false, 0.019738186035103217 },
        new Object[] { 7, 78.55, "Month-to-month", "Fiber optic", "Bank transfer (automatic)", false, true, false, false, false, false, true, false, false, false, true, true, 0.6018385204203486 },
        new Object[] { 54, 20.1, "Two year", "No", "Mailed check", false, false, false, false, false, false, false, false, false, false, true, false, 0.010356440052814584 },
        new Object[] { 2, 20.65, "Month-to-month", "No", "Mailed check", false, false, false, false, false, false, false, false, false, false, true, false, 0.18123881305168948 },
        new Object[] { 71, 105.15, "Two year", "Fiber optic", "Bank transfer (automatic)", false, true, true, false, true, true, true, false, true, false, true, true, 0.07933588610988956 },
        new Object[] { 60, 105.9, "Month-to-month", "Fiber optic", "Electronic check", false, true, true, false, true, true, true, false, false, false, true, true, 0.41655667471812763 },
        new Object[] { 33, 24.15, "One year", "No", "Credit card (automatic)", false, false, false, false, false, false, false, false, true, true, true, true, 0.03647299756062355 },
        new Object[] { 7, 20.65, "Month-to-month", "No", "Mailed check", false, false, false, false, false, false, false, false, false, false, true, false, 0.15804235892788476 }
    };

    /** Predicted vs observed churn rate in each fifth of the held-out set. */
    static final double[][] CALIBRATION = {
        { 0.015540705061562873, 0.014184397163120567 },
        { 0.06838806634835855, 0.0851063829787234 },
        { 0.1998092283245022, 0.2206405693950178 },
        { 0.4116911702156383, 0.35587188612099646 },
        { 0.6675622764405105, 0.6548042704626335 }
    };
}
