package com.jayraj.churnpredictor;

/** GENERATED by tools/generate_model.py from model/model.json. Do not edit by hand. */
final class ModelData {
    private ModelData() {}

    static final String ALGORITHM = "Logistic regression (L2, unweighted)";
    static final String TRAINED_ON = "IBM Telco Customer Churn";

    // Provenance, copied from model/model.json (which the web app's trainer writes).
    static final String MODEL_VERSION = "1.0.0";
    static final String TRAINED_DATE = "2026-09-25";
    static final String TRAINING_COMMIT = "3d29b62fd9fee2bfeff319ce71178fb6d6e53f9b";
    static final String DATA_SHA256 = "3d5c233415c1b42bdea7172c73e620819f507f0a8294bc2337a1d8a8877feef0";
    static final String COEFFICIENTS_SHA256 = "9980bb7b487a561a9086f10049df4a58ad78e8153aaceff34e25fb06110be202";
    static final String FEATURE_SCHEMA_SHA256 = "ec6a732391ab0a2ef88d5a263bbf9c73a19a6ee1ca1d9b58994e4e78752b8c4b";
    static final String SKLEARN_VERSION = "1.9.1";

    static final int N_TRAIN = 5625;
    static final int N_TEST = 1407;
    static final double BASE_RATE = 0.26578498293515357;
    static final double ROC_AUC = 0.8336836274596082;
    static final double ROC_AUC_LOW = 0.8108419641125106;
    static final double ROC_AUC_HIGH = 0.8555450469607762;

    static final double INTERCEPT = 0.28436071285206377;

    /** Feature order; matches COEF and MEANS. */
    static final String[] KEYS = {
        "tenure",
        "monthlyCharges",
        "seniorCitizen",
        "partner",
        "dependents",
        "phoneService",
        "multipleLines",
        "onlineSecurity",
        "onlineBackup",
        "deviceProtection",
        "techSupport",
        "streamingTV",
        "streamingMovies",
        "paperlessBilling",
        "contractOneYear",
        "contractTwoYear",
        "internetFiber",
        "internetNone",
        "payMailedCheck",
        "payBankTransfer",
        "payCreditCard"
    };

    /** Coefficients in raw feature units. */
    static final double[] COEF = {
        -0.032977946863321644,
        -0.005458794943472678,
        0.19486820650562472,
        -0.029169391459754914,
        -0.24204948666925633,
        -0.4031106171833308,
        0.3661289104343081,
        -0.3733538137985904,
        -0.11859858381681172,
        0.0758423207164359,
        -0.33173408677337557,
        0.3556860023549066,
        0.32880588775908054,
        0.29275372559243357,
        -0.7441754630411589,
        -1.3399085050653994,
        1.0379700456059187,
        -0.943904966579909,
        -0.2666419993480737,
        -0.38673870239583735,
        -0.3420058728583642
    };

    /** Training-set mean of each feature, the "average customer". */
    static final double[] MEANS = {
        32.562311111111114,
        64.99931555555555,
        0.16177777777777777,
        0.48604444444444445,
        0.2995555555555556,
        0.9031111111111111,
        0.424,
        0.2869333333333333,
        0.3504,
        0.3456,
        0.29475555555555555,
        0.38897777777777776,
        0.39022222222222225,
        0.5953777777777778,
        0.21013333333333334,
        0.24142222222222223,
        0.4414222222222222,
        0.21475555555555556,
        0.22542222222222222,
        0.21955555555555556,
        0.216
    };

    static final String[] LABELS = {
        "Tenure (months)",
        "Monthly bill",
        "Senior citizen",
        "Has a partner",
        "Has dependents",
        "Phone service",
        "Multiple phone lines",
        "Online security",
        "Online backup",
        "Device protection",
        "Tech support",
        "Streaming TV",
        "Streaming movies",
        "Paperless billing",
        "One-year contract",
        "Two-year contract",
        "Fibre-optic internet",
        "No internet service",
        "Pays by mailed check",
        "Pays by bank transfer",
        "Pays by credit card"
    };
}
