"""Generate the Java model constants and test fixtures from model/model.json.

model.json is the artifact exported by the web app's trainer
(https://github.com/jayraj0975/churnapp, scripts/train_model.py): a logistic
regression fitted on IBM's Telco churn data, in raw feature units. This script
turns it into plain Java so the Android app scores customers with no runtime
dependencies and the unit tests can compare against scikit-learn's own numbers.

Run from the repo root:  python3 tools/generate_model.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PKG = "com.jayraj.churnpredictor"
SRC = ROOT / "app/src/main/java" / PKG.replace(".", "/")
TEST = ROOT / "app/src/test/java" / PKG.replace(".", "/")
m = json.loads((ROOT / "model/model.json").read_text())

keys = list(m["coefficients"])


def arr(values, fmt=repr):
    return ",\n        ".join(fmt(v) for v in values)


def jstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


(SRC / "ModelData.java").write_text(f'''package {PKG};

/** GENERATED by tools/generate_model.py from model/model.json. Do not edit by hand. */
final class ModelData {{
    private ModelData() {{}}

    static final String ALGORITHM = {jstr(m["algorithm"])};
    static final String TRAINED_ON = {jstr(m["trainedOn"])};
    static final int N_TRAIN = {m["nTrain"]};
    static final int N_TEST = {m["nTest"]};
    static final double BASE_RATE = {m["baseRate"]!r};
    static final double ROC_AUC = {m["metrics"]["rocAuc"]!r};
    static final double ROC_AUC_LOW = {m["metrics"]["rocAucCi95"][0]!r};
    static final double ROC_AUC_HIGH = {m["metrics"]["rocAucCi95"][1]!r};

    static final double INTERCEPT = {m["intercept"]!r};

    /** Feature order; matches COEF and MEANS. */
    static final String[] KEYS = {{
        {arr(keys, jstr)}
    }};

    /** Coefficients in raw feature units. */
    static final double[] COEF = {{
        {arr(m["coefficients"][k] for k in keys)}
    }};

    /** Training-set mean of each feature, the "average customer". */
    static final double[] MEANS = {{
        {arr(m["means"][k] for k in keys)}
    }};

    static final String[] LABELS = {{
        {arr((m["features"][k]["label"] for k in keys), jstr)}
    }};
}}
''')

rows = []
for g in m["golden"]:
    p = g["profile"]
    rows.append(
        f'        new Object[] {{ {p["tenure"]}, {p["monthlyCharges"]!r}, {jstr(p["contract"])}, '
        f'{jstr(p["internetService"])}, {jstr(p["paymentMethod"])}, '
        + ", ".join(str(p[k]).lower() for k in (
            "onlineSecurity", "onlineBackup", "deviceProtection", "techSupport", "streamingTV",
            "streamingMovies", "paperlessBilling", "seniorCitizen", "partner", "dependents",
            "phoneService", "multipleLines"))
        + f', {g["probability"]!r} }}')

(TEST / "GoldenData.java").write_text(f'''package {PKG};

/** GENERATED by tools/generate_model.py: real customers with scikit-learn's own predictions. */
final class GoldenData {{
    private GoldenData() {{}}

    /** tenure, monthlyCharges, contract, internet, payment, then 12 booleans, then probability. */
    static final Object[][] ROWS = {{
{(",\n").join(rows)}
    }};

    /** Predicted vs observed churn rate in each fifth of the held-out set. */
    static final double[][] CALIBRATION = {{
        {arr(([b["predicted"], b["observed"]] for b in m["calibration"]), lambda r: "{ %r, %r }" % tuple(r))}
    }};
}}
''')
print("generated", len(keys), "features,", len(rows), "golden rows")
